name: MzLib
version: ${version}
authors:
 - "Lv Yitian"
 - "mz"
 - "Yurinann"
 - "泡泡🍥"
 - "钟小白Core"
 - "hpwriterkyle"
main: mz.mzlib.minecraft.bukkit.MzLibBukkitPlugin
loadbefore: [ QuickShop ]
softdepend: [ PlugMan ]
api-version: 1.13
