name: 问题反馈
description: 描述问题并提交，帮助我们对其进行检查与修复。
labels: ["Type: Bug"]
body:
  - type: textarea
    attributes:
      label: 描述问题
      description: 请告诉我们您遇到了什么问题。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 期望的效果
      description: 请告诉我们您期望的正常运行时的效果。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 复现步骤
      description: 请告诉我们此问题的复现步骤。
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: 错误日志
      description: |
        提交可能出现的错误日志，请注意隐藏私密信息。
        我们建议您首先粘贴至在线剪贴板（例如 `paste.fastmirror.net`），随后在此处附上链接。
      placeholder: https://paste.fastmirror.net/
    validations:
      required: false
      
  - type: input
    attributes:
      label: 服务端核心版本
      description: 请填写您使用的服务端核心版本。
      placeholder: Spigot 1.12.2
    validations:
      required: true

  - type: input
    attributes:
      label: MzLib 版本
      description: 请填写您使用的 MzLib 版本。（请勿填写 "latest"）。
      placeholder: 10.0.1-pre48-test10
    validations:
      required: true

  - type: textarea
    attributes:
      label: 其他信息
      description: 如果您有其他上述未提到的信息，可以在此处补充，例如一张截图或一段视频，这会帮助我们更快地解决问题。
    validations:
      required: false
      
  - type: checkboxes
    attributes:
      label: 最终检查
      description: 在最终提交前，请检查您是否满足了以下所有条件。
      options:
        - label: 我正在使用 MzLib 的最新版本。
          required: true
        - label: 我已经阅读了 MzLib 的 Wiki 且确定此问题不是由于错误的配置文件引起的。
          required: true
        - label: 在我未认真阅读完检查部分时，我选择了所有的 Checkbox。
          required: false
        - label: 我确定 MzLib 没有运行在其不支持的环境上。
          required: true
