name: 功能建议
description: 希望我们提供更多的功能。
title: "[Enhancement] "
labels: ["Type: Bug"]
assignees: [ mzmzpwq, Yurinann ]

body:
  - type: textarea
    id: feature-request
    attributes:
      label: 描述功能
      description: 请详细描述你想要的功能。
    validations:
      required: true
      
  - type: textarea
    id: request-reason
    attributes:
      label: 建议原因
      description: 请告诉我们您希望在 MzLib 中添加此功能的原因。
    validations:
      required: true
      
  - type: textarea
    id: additional-info
    attributes:
      label: 其他信息
      description: 如果您有其他上述未提到的信息，可以在此处补充。
    validations:
      required: false

  - type: checkboxes
    id: final-check
    attributes:
      label: 最终检查
      description: 在最终提交前，请检查您是否满足了以下所有条件。
      options:
        - label: 我正在使用 MzLib 的最新版本，并确定最新版中没有此功能。
          required: true
        - label: 我在未认真阅读完检查部分的情况下选择了这个 Checkbox。
          required: false
        - label: 我确定此功能不会影响到 MzLib 的现有架构。
          required: true
