name: MzLib
version: ${version}
authors:
  - "lvyitian"
  - "mz"
  - "Yurinann"
  - "awa"
  - "Core2002"
  - "hpwriterkyle"
  - "pi_ka"
main: mz.mzlib.minecraft.bukkit.MzLibBukkitPlugin
api-version: 1.13
folia-supported: true
