name: MzLib
version: ${version}
authors:
 - "lvyitian"
 - "mz"
 - "Yurinann"
 - "awa"
 - "Core2002"
 - "hpwriterkyle"
main: mz.mzlib.minecraft.bukkit.MzLibBukkitPlugin
softdepend: [ PlugMan ]
api-version: 1.13
