name: MzLib
version: ${version}
authors:
 - "lvyitian"
 - "mz"
 - "Yurinann"
 - "awa"
 - "Core2002"
 - "hpwriterkyle"
 - "SharkGod"
main: mz.mzlib.minecraft.bukkit.MzLibBukkitPlugin
api-version: 1.13
